"use client";

import React from "react";
import VehicleHealthReport, { computeScore } from "@/components/vehicle-health-report/VehicleHealthReport";
import type { VHIData } from "@/components/vehicle-health-report/VehicleHealthReport";

const mockData: VHIData = {
  vehicle: {
    year: 2019,
    make: "Honda",
    model: "CR-V",
    engine: "1.5L L4 Turbo",
  },
  vin: "2HKRW2H53KH123456",
  currentMiles: 87432,
  customerName: "Sarah Mitchell",
  buckets: {
    overdue: [
      {
        key: "brake_pads_front",
        serviceKey: "brake_pads_front",
        title: "Front Brake Pads",
        category: "Brakes",
        intervalMiles: 40000,
        intervalMonths: 48,
        last: { miles: 42150, date: "2022-06-14T00:00:00.000Z", source: "carfax" },
        dueAtMiles: 82150,
        dueAtDate: "2026-06-14T00:00:00.000Z",
        milesToGo: -5282,
        daysToGo: -120,
        bump: "red",
        source: "oem",
        dviSource: "tekmetric",
        reason: null,
        usingShopInterval: false,
        declined: true,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
      {
        key: "transmission_fluid",
        serviceKey: "transmission_fluid",
        title: "Transmission Fluid",
        category: "Drivetrain",
        intervalMiles: 60000,
        intervalMonths: 72,
        last: null,
        dueAtMiles: 60000,
        dueAtDate: null,
        milesToGo: -27432,
        daysToGo: null,
        bump: null,
        source: "oem",
        dviSource: null,
        reason: "Never performed",
        usingShopInterval: false,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
      {
        key: "engine_air_filter",
        serviceKey: "engine_air_filter",
        title: "Engine Air Filter",
        category: "Engine",
        intervalMiles: 30000,
        intervalMonths: 36,
        last: { miles: 55200, date: "2023-09-20T00:00:00.000Z", source: "shop" },
        dueAtMiles: 85200,
        dueAtDate: "2026-09-20T00:00:00.000Z",
        milesToGo: -2232,
        daysToGo: -45,
        bump: null,
        source: "oem",
        dviSource: null,
        reason: null,
        usingShopInterval: false,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
      {
        key: "dvi_finding_cv_axle_boot_torn",
        serviceKey: null,
        title: "CV Axle Boot Torn",
        category: "DVI Finding",
        intervalMiles: null,
        intervalMonths: null,
        last: null,
        dueAtMiles: null,
        dueAtDate: null,
        milesToGo: null,
        daysToGo: null,
        bump: "red",
        source: "dvi",
        dviSource: "tekmetric",
        reason: null,
        usingShopInterval: false,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
      {
        key: "oil_replacement_reminder",
        serviceKey: "oil_reminder",
        title: "Reset the oil replacement reminder (i.e. MAINT REQD).",
        category: "General",
        intervalMiles: 5000,
        intervalMonths: 6,
        last: null,
        dueAtMiles: 5000,
        dueAtDate: null,
        milesToGo: -82432,
        daysToGo: null,
        bump: "red",
        source: "oem",
        dviSource: null,
        reason: null,
        usingShopInterval: false,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
      {
        key: "chassis_body_tighten",
        serviceKey: "chassis_body",
        title: "Tighten nuts and bolts on chassis and body",
        category: "Body",
        intervalMiles: 5000,
        intervalMonths: 6,
        last: null,
        dueAtMiles: 5000,
        dueAtDate: null,
        milesToGo: -82432,
        daysToGo: null,
        bump: "red",
        source: "oem",
        dviSource: null,
        reason: null,
        usingShopInterval: false,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
    ],
    dueSoon: [
      {
        key: "spark_plugs",
        serviceKey: "spark_plugs",
        title: "Spark Plugs",
        category: "Engine",
        intervalMiles: 60000,
        intervalMonths: null,
        last: { miles: 28500, date: "2021-03-10T00:00:00.000Z", source: "carfax" },
        dueAtMiles: 88500,
        dueAtDate: null,
        milesToGo: 1068,
        daysToGo: 33,
        bump: null,
        source: "oem",
        dviSource: null,
        reason: null,
        usingShopInterval: false,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
      {
        key: "cabin_air_filter",
        serviceKey: "cabin_air_filter",
        title: "Cabin Air Filter",
        category: "Engine",
        intervalMiles: 15000,
        intervalMonths: 12,
        last: { miles: 74300, date: "2025-04-05T00:00:00.000Z", source: "shop" },
        dueAtMiles: 89300,
        dueAtDate: "2026-04-05T00:00:00.000Z",
        milesToGo: 1868,
        daysToGo: 23,
        bump: null,
        source: "oem",
        dviSource: null,
        reason: null,
        usingShopInterval: true,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
      {
        key: "brake_fluid",
        serviceKey: "brake_fluid",
        title: "Brake Fluid",
        category: "Brakes",
        intervalMiles: null,
        intervalMonths: 36,
        last: { miles: 55200, date: "2023-09-20T00:00:00.000Z", source: "shop" },
        dueAtMiles: null,
        dueAtDate: "2026-09-20T00:00:00.000Z",
        milesToGo: null,
        daysToGo: 68,
        bump: "yellow",
        source: "oem",
        dviSource: "tekmetric",
        reason: null,
        usingShopInterval: false,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
    ],
    upcoming: [
      {
        key: "oil_change",
        serviceKey: "oil_change",
        title: "Oil & Filter",
        category: "Engine",
        intervalMiles: 7500,
        intervalMonths: 12,
        last: { miles: 84900, date: "2025-11-02T00:00:00.000Z", source: "shop" },
        dueAtMiles: 92400,
        dueAtDate: "2026-11-02T00:00:00.000Z",
        milesToGo: 4968,
        daysToGo: 234,
        bump: null,
        source: "oem",
        dviSource: null,
        reason: null,
        usingShopInterval: true,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
      {
        key: "tires_rotate",
        serviceKey: "tires_rotate",
        title: "Tire Rotation",
        category: "Tires & Wheels",
        intervalMiles: 7500,
        intervalMonths: 6,
        last: { miles: 84900, date: "2025-11-02T00:00:00.000Z", source: "shop" },
        dueAtMiles: 92400,
        dueAtDate: "2026-05-02T00:00:00.000Z",
        milesToGo: 4968,
        daysToGo: 50,
        bump: null,
        source: "oem",
        dviSource: null,
        reason: null,
        usingShopInterval: false,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
      {
        key: "coolant",
        serviceKey: "coolant",
        title: "Cooling System",
        category: "Engine",
        intervalMiles: 60000,
        intervalMonths: 60,
        last: { miles: 55200, date: "2023-09-20T00:00:00.000Z", source: "shop" },
        dueAtMiles: 115200,
        dueAtDate: "2028-09-20T00:00:00.000Z",
        milesToGo: 27768,
        daysToGo: 854,
        bump: null,
        source: "oem",
        dviSource: null,
        reason: null,
        usingShopInterval: false,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
      {
        key: "differential_rear",
        serviceKey: "differential_rear",
        title: "Differential Fluid",
        category: "Drivetrain",
        intervalMiles: 60000,
        intervalMonths: null,
        last: { miles: 55200, date: "2023-09-20T00:00:00.000Z", source: "shop" },
        dueAtMiles: 115200,
        dueAtDate: null,
        milesToGo: 27768,
        daysToGo: null,
        bump: null,
        source: "oem",
        dviSource: null,
        reason: null,
        usingShopInterval: false,
        declined: false,
        matchedDeferred: null,
        protractorDeferredId: null,
      },
    ],
  },
};

export default function DemoReportPage() {
  const score = computeScore(mockData);

  return (
    <VehicleHealthReport
      data={mockData}
      score={score}
      shopName="Mitchell's Auto Care"
      shopPhone="(555) 234-5678"
    />
  );
}
