import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: "./lib/db/schema/index.ts",
  out: "./drizzle",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATAONE_DATABASE_URL!,
  },
  tablesFilter: [
    "conversations",
    "conversation_messages",
    "conversation_participants",
    "phone_numbers",
    "sms_contacts",
    "sms_messages",
    "voicemails",
    "call_transcriptions",
    "rescue_rover_settings",
    "rescue_rover_call_logs",
    "rescue_rover_safety_rules",
    "rescue_rover_prompt_templates",
    "rescue_rover_voice_scripts",
    "rescue_rover_context_rules",
    "rescue_rover_rcs_links",
    "api_usage_logs",
    "crm_agencies",
    "crm_corporate_branding",
    "crm_branding_themes",
    "crm_parent_organizations",
    "crm_accounts",
    "crm_locations",
    "crm_user_types",
    "crm_agency_pricing_packages",
    "onboarding_stages",
    "onboarding_stage_assignments",
    "onboarding_steps",
    "onboarding_stage_steps",
    "onboarding_checklists",
    "onboarding_step_checklists",
    "onboarding_cards",
    "onboarding_card_progress",
    "tours",
    "user_tour_progress",
    "onboarding_guides_content",
    "user_onboarding_guide_progress",
    "workflow_sequences",
    "user_workflow_sequence_progress",
    "banners",
    "user_banner_progress",
    "user_favorites",
    "content_assignments",
    "crm_contacts",
    "crm_contact_role_types",
    "crm_contact_agency_assignments",
    "crm_contact_parent_org_assignments",
    "crm_contact_account_assignments",
    "crm_contact_location_assignments",
    "crm_entity_notes",
    "crm_entity_tasks",
    "normalized_vehicles",
    "normalized_customers",
    "normalized_work_orders",
    "normalized_service_jobs",
    "normalized_line_items",
    "normalized_payments",
  ],
});
