import { defineConfig } from "drizzle-kit";

export default defineConfig({
  schema: "./lib/db/schema/index.ts",
  out: "./drizzle",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATAONE_DATABASE_URL!,
  },
  tablesFilter: [
    "conversations",
    "conversation_messages",
    "conversation_participants",
    "phone_numbers",
    "sms_contacts",
    "sms_messages",
    "voicemails",
    "call_transcriptions",
    "api_usage_logs",
    "normalized_vehicles",
    "normalized_customers",
    "normalized_work_orders",
    "normalized_service_jobs",
    "normalized_line_items",
    "normalized_payments",
    "support_tickets",
    "production_logs",
    "sniffer_sessions",
    "tekmetric_migration_runs",
    "tekmetric_migration_dumps",
    "tekmetric_migration_mappings",
    "tekmetric_migration_audit",
    "dataone_cache",
    "dataone_oe",
    "lkp_ymm_maintenance_interval",
    "def_maintenance_event",
    "dataone_lkp_squish_maintenance",
    "part_cross_ref",
    "knowledge_articles",
    "viewed_vins",
    "sync_metrics",
    "ingestion_errors",
    "data_quality_reports",
    "extension_analytics",
    "system_announcements",
    "sms_historical_work_orders",
    "ratelimits",
  ],
});
