import assert from "node:assert/strict";
import {deferRecoveryWindow,windowReady} from "../lib/jwt-recovery-deferrals";
import {nextEligibleWindow,recoverySchedule,scheduleCheckpoint} from "../lib/jwt-overnight-scheduler";
const windows=["233:2026-08-25","235:2026-08-01"];
const schedule=recoverySchedule(windows,{cursor:0,page:1});
let deferred=deferRecoveryWindow(undefined,1,1,"update","57014",0);
assert.equal(windowReady(deferred,59999),false);
assert.equal(windowReady(deferred,60000),true);
assert.equal(nextEligibleWindow(windows,schedule.completed,(_shop,key)=>key!==windows[0]||windowReady(deferred,1)),1);
schedule.completed.add(windows[1]);
const checkpoint=scheduleCheckpoint(windows,schedule.completed,schedule.pages);
assert.equal(checkpoint.cursor,0);
assert.equal(checkpoint.page,1);
assert.equal(checkpoint.completedWindows,1);
assert.equal(recoverySchedule(windows,checkpoint).completed.has(windows[0]),false,"timeout is not completion");
for(let i=0;i<3;i++)deferred=deferRecoveryWindow(deferred,1,1,"update","57014",1000);
assert.equal(deferred.attempts,4);
assert.equal(deferred.exhausted,true);
assert.equal(windowReady(deferred,1e12),false,"permanent failures cannot retry forever");
assert.equal(deferred.page,1);
assert.equal(windowReady(undefined),true,"successful page removes deferral");
console.log("PASS timeout deferral, restart checkpoints, other-shop progress and bounded exhaustion");
