import assert from "node:assert/strict";
import {resolveRecoveryVehicle as resolve} from "../lib/jwt-recovery-vehicle-resolution";
const si={ID:"provider-vehicle",VIN:"1HGCM82633A004352",Year:2018,Make:"Honda",Model:"CR-V"};
const source={ServiceItem:si};
const old={vehicle_id:"previous",raw_data:{rawPayload:{ServiceItem:{ID:si.ID}}}};
const previous={id:"previous",vin:null,year:2018,make:"Honda",model:"Crv"};
const exact={...previous,id:"exact",vin:si.VIN};
assert.equal(resolve(source,old,[previous]).vehicle.id,"previous");
assert.equal(resolve(source,old,[previous,exact]).vehicle.id,"exact");
assert.equal(resolve({ServiceItem:{...si,VIN:"",Lookup:"123456"}},old,[previous]).vehicle.id,"previous");
assert.throws(()=>resolve(source,{...old,raw_data:{}},[previous,exact]));
assert.throws(()=>resolve(source,old,[{...previous,year:2012}]));
assert.throws(()=>resolve(source,old,[{...previous,vin:"1HGCM82633A004353"},exact]));
assert.throws(()=>resolve(source,old,[{...previous,soft_delete:{isDeleted:true}}]));
assert.throws(()=>resolve(source,undefined,[exact,{...exact,id:"duplicate"}]));
assert.throws(()=>resolve({ServiceItem:{...si,VIN:"NA"}},undefined,[]));
assert.equal(resolve(source,undefined,[]).vehicle,undefined);
assert.equal(resolve(source,undefined,[exact]).vehicle.id,"exact");
assert.equal(resolve(source,old,[{...previous,year:2012},exact],{replaceFromInvoice:true}).vehicle.id,"exact");
assert.equal(resolve(source,old,[{...previous,year:2012}],{replaceFromInvoice:true}).vehicle,undefined);
assert.equal(resolve({ServiceItem:{...si,VIN:"NA"}},undefined,[{...exact,vin:"NA"}],{unknownVehicle:true}).unlinked,true);
assert.throws(()=>resolve(source,undefined,[],{unknownVehicle:true}));
assert.throws(()=>resolve({ServiceItem:{...si,VIN:"NA"}},old,[],{unknownVehicle:true}));
console.log("Recovery vehicle identity safeguards: PASS");
