import { test, expect } from '@playwright/test';

test('Burnett evidence, branding inheritance, uploads, reload and reset remain isolated', async ({page,baseURL})=>{
  const requests:string[]=[]; const errors:string[]=[];
  page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));
  const id=(s:string)=>page.getByTestId(s);
  const color=()=>page.locator('.dd').evaluate(e=>(e as HTMLElement).style.getPropertyValue('--forest'));
  await page.goto('/');
  await expect(id('demo-dataset')).toHaveValue('burnett');
  await expect(id('lane-t4')).toContainText('Jason Roby');
  await id('vehicle-v1').click();
  await expect(id('workflow-job-j1')).toContainText('YTD package reference');
  await id('complete-j1').click();await expect(id('start-j2')).toBeEnabled();
  await page.keyboard.press('Escape');
  await id('nav-experience').click();
  await id('experience-search').fill('Jason Roby');
  await expect(page.locator('.evidence-card')).toHaveCount(1);
  await expect(page.locator('.evidence-card')).toContainText('811');
  await expect(id('experience-view')).toContainText('99.78%');
  await id('nav-branding').click();
  await id('brand-name').fill('Burnett Automotive');
  await id('brand-primary').fill('#ffffff');
  await id('apply-branding').click();
  expect(await color()).toBe('#ffffff');
  expect(await page.locator('.dd').evaluate(e=>(e as HTMLElement).style.getPropertyValue('--primary-foreground'))).toBe('#000000');
  await id('brand-scope').selectOption('location');
  await id('brand-inherit').uncheck();
  await id('brand-name').fill('Burnett presentation shop');
  await id('brand-primary').fill('#173a65');
  await id('apply-branding').click();
  expect(await color()).toBe('#173a65');
  await id('brand-scope').selectOption('enterprise');
  await id('brand-primary').fill('#8b2525');
  await id('apply-branding').click();
  expect(await color()).toBe('#173a65');
  await id('brand-location').selectOption('example');
  await id('apply-branding').click();
  expect(await color()).toBe('#8b2525');
  await page.reload();
  expect(await color()).toBe('#8b2525');
  await id('nav-branding').click();
  await id('brand-location').selectOption('ytd');
  await id('brand-scope').selectOption('location');
  await id('brand-inherit').check();
  await id('apply-branding').click();
  expect(await color()).toBe('#8b2525');
  await id('brand-scope').selectOption('enterprise');
  await id('brand-logo').setInputFiles({name:'bad.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')});
  await expect(id('brand-logo-error')).toBeVisible();
  const png=await page.screenshot();
  await id('brand-logo').setInputFiles({name:'test.png',mimeType:'image/png',buffer:png});
  await expect(id('remove-brand-logo')).toBeVisible();
  await id('apply-branding').click();
  await expect(page.locator('.sidebar img')).toBeVisible();
  await page.reload();await expect(page.locator('.sidebar img')).toBeVisible();
  await id('nav-branding').click();await id('remove-brand-logo').click();await id('apply-branding').click();
  await expect(page.locator('.sidebar img')).toHaveCount(0);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await id('reset-branding').click();await id('confirm-reset-branding').click();
  expect(await color()).toBe('#285746');
  await id('nav-dispatch').click();await id('reset-demo').click();await id('confirm-action').click();
  await expect(id('demo-dataset')).toHaveValue('burnett');
  await expect(id('shop-clock')).toHaveText('10:15');
  expect(errors).toEqual([]);
  expect(requests.filter(url=>!url.startsWith(baseURL!)&&!url.startsWith('data:'))).toEqual([]);
  expect(requests.filter(url=>new URL(url).pathname.startsWith('/api/'))).toEqual([]);
});
