import { test, expect } from '@playwright/test';

test('connected dispatch / vehicle / technician scenario stays local and resets', async ({ page, baseURL }) => {
  const requests: string[] = [];
  const errors: string[] = [];
  page.on('request', r => requests.push(r.url()));
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  const id = (s: string) => page.getByTestId(s);
  await id('demo-dataset').selectOption('fictional');
  await id('confirm-action').click();
  await expect(id('dispatch-view')).toBeVisible();
  for(let n=1;n<=6;n++) await expect(id(`lane-t${n}`)).toBeVisible();
  await expect(id('lane-rack')).toBeVisible();
  await expect(page.locator('[data-testid^="vehicle-v"]')).toHaveCount(10);
  await id('vehicle-v1').click();
  await expect(id('start-j2')).toBeDisabled();
  await id('pause-j1').click();
  await id('pause-reason').selectOption('Waiting for parts');
  await id('confirm-action').click();
  await page.keyboard.press('Escape');
  await id('advance-clock').click();
  await id('vehicle-v1').click();
  await expect(id('workflow-job-j1')).toContainText('22m active session');
  await expect(id('workflow-job-j1')).toContainText('15m paused waiting');
  await id('edit-j5').click();
  await id('assignment-tech').selectOption('t2');
  await id('assignment-start').fill('10:30');
  await id('confirm-action').click();
  await expect(id('workflow-job-j5')).toContainText('Eli Mercer');
  await id('start-j1').click();
  await id('complete-j1').click();
  await expect(id('start-j2')).toBeEnabled();
  await expect(id('start-j3')).toBeDisabled();
  await page.keyboard.press('Escape');
  await expect(id('vehicle-v1')).toBeFocused();
  await id('demo-role').selectOption('technician');
  await id('demo-technician').selectOption('t2');
  await expect(id('my-work-view')).toBeVisible();
  await id('start-j5').click();
  await id('start-j2').click();
  await expect(id('switch-form')).toBeVisible();
  await id('confirm-action').click();
  await expect(id('my-job-j5')).toContainText('Switched to another job');
  await expect(id('pause-j2')).toBeVisible();
  await id('demo-role').selectOption('dispatcher');
  await expect(id('lane-t2')).toContainText('Oil & filter');
  await id('reset-demo').click();
  await id('confirm-action').click();
  await expect(id('shop-clock')).toHaveText('10:15');
  await page.getByRole('textbox',{name:'Search vehicles'}).fill('not-a-car');
  await expect(page.getByText('No vehicles match')).toBeVisible();
  await page.getByRole('button',{name:'Clear search'}).click();
  await id('vehicle-v1').click();
  await expect(id('pause-j1')).toBeVisible();
  await expect(id('workflow-job-j5')).toContainText('Tess Rowan');
  await page.keyboard.press('Escape');
  await id('demo-role').selectOption('technician');
  await page.setViewportSize({width:390,height:844});
  await expect(id('my-work-view')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const box = await id('pause-j1').boundingBox();
  expect(box?.height).toBeGreaterThanOrEqual(44);
  await id('pause-j1').click();
  await page.keyboard.press('Escape');
  await expect(id('pause-j1')).toBeFocused();
  await page.screenshot({path:'test-results/my-work-mobile.png',fullPage:true});
  expect(errors).toEqual([]);
  expect(requests.filter(url => !url.startsWith(baseURL!) && !url.startsWith('data:'))).toEqual([]);
  expect(requests.filter(url => new URL(url).pathname.startsWith('/api/'))).toEqual([]);
});
