import { ArrowRight, CheckCheck, FileCheck2 } from 'lucide-react';
import { composeInspectionLines, getCompletionErrors, getPricingErrors, isCompleted, isReviewed, recommendationTotal, ticketTotal, type DemoState, type DemoAction } from '../../model';
import { Always, Button, Field, InspectionLines, money, Panel } from './Common';

export function Advisor({ state, dispatch, onCustomer, onTechnician }: { state: DemoState; dispatch: (a: DemoAction) => boolean; onCustomer: () => void; onTechnician: () => void }) {
  const errors = getCompletionErrors(state);
  const pricingErrors = getPricingErrors(state);
  return <div data-testid="advisor-view"><div className="page-heading"><div><div className="eyebrow">02 / Advisor · Eli Mercer</div><h1>A clear record. A considered recommendation.</h1><p>Review the inspection first. Keep documentation separate from proposed work and fictional pricing.</p></div><span className={`badge ${isReviewed(state) ? '' : 'yellow'}`}>{isReviewed(state) ? 'Current revision reviewed' : 'Review required'}</span></div>
    {!isCompleted(state) && <div className="notice" role="status"><strong>Current inspection is not complete.</strong> Findings are a draft. {errors.length ? `${errors.length} required corrections remain.` : 'Confirm completion in the technician view.'}<div className="actions"><Button onClick={onTechnician}>Return to technician</Button></div></div>}
    <div className="layout"><div className="stack">
      <Panel title="Inspection documentation package" description="Protractor-style ticket preview · inspection only, no performed repair claim." badge={<span className="mono badge">$0.00 · required</span>}><div className="notice success"><Always /> Every completed required item is retained, including green findings. Uninspected and unable-to-test entries are explicitly identified.</div><InspectionLines lines={composeInspectionLines(state)} /><div className="total"><span>Inspection documentation</span><strong>$0.00</strong></div></Panel>
      <Panel title="Optional recommendation packages" description="Editable fictional estimate. Proposed work only — not customer-authorized or performed.">{state.recommendations.map(r => <section key={r.id} className="check-row" data-testid={`recommendation-${r.id}`}><label className="library-option"><input type="checkbox" aria-label={`Include ${r.title}`} checked={r.selected} onChange={e => dispatch({ type: 'recommendation', id: r.id, patch: { selected: e.target.checked } })} /><strong>{r.title}</strong><span className="badge yellow">Proposed only</span></label>
        {r.selected && <><Field label={`${r.id} recommendation title`} value={r.title} onChange={title => dispatch({ type: 'recommendation', id: r.id, patch: { title } })} /><div className="price-row"><Field label={`${r.id} part description`} value={r.part} onChange={part => dispatch({ type: 'recommendation', id: r.id, patch: { part } })} /><Field label={`${r.id} parts quantity`} type="number" min={0} max={100} step="1" value={r.quantity} onChange={quantity => dispatch({ type: 'recommendation', id: r.id, patch: { quantity } })} /><Field label={`${r.id} unit price ($)`} type="number" min={0} max={10000} step="0.01" value={r.unitPrice} onChange={unitPrice => dispatch({ type: 'recommendation', id: r.id, patch: { unitPrice } })} /></div><div className="price-row"><Field label={`${r.id} labor description`} value={r.labor} onChange={labor => dispatch({ type: 'recommendation', id: r.id, patch: { labor } })} /><Field label={`${r.id} labor hours`} type="number" min={0} max={100} value={r.hours} onChange={hours => dispatch({ type: 'recommendation', id: r.id, patch: { hours } })} /><Field label={`${r.id} labor rate ($/hour)`} type="number" min={0} max={10000} step="0.01" value={r.laborRate} onChange={laborRate => dispatch({ type: 'recommendation', id: r.id, patch: { laborRate } })} /></div><div className="total"><span>Proposed package subtotal</span><strong>{money(recommendationTotal(r))}</strong></div></>}
      </section>)}</Panel>
      {pricingErrors.length > 0 && <div className="notice error" role="alert"><strong>Correct the estimate before review</strong><ul>{pricingErrors.map(e => <li key={e}>{e}</li>)}</ul></div>}
      <div className="sticky-actions"><div><strong>Review this exact revision</strong><p>Editing any finding, evidence or price invalidates completion and review.</p></div><Button primary disabled={!isCompleted(state) || pricingErrors.length > 0} data-testid="review-ticket" onClick={() => dispatch({ type: 'review' })}><CheckCheck /> Confirm advisor review</Button></div>
    </div><aside className="guide"><FileCheck2 /><div className="eyebrow" style={{ marginTop: 15 }}>Ticket preview / fictional RO 2086</div><h2>Documentation, then decisions.</h2><div className="line-top" style={{ marginTop: 25 }}><span>Required inspection</span><strong className="mono">$0.00</strong></div><div className="line-top"><span>Proposed packages</span><strong>{state.recommendations.filter(r => r.selected).length}</strong></div><div className="total"><span>Estimate total</span><strong data-testid="ticket-total">{money(ticketTotal(state))}</strong></div><p className="hint">USD. Tax and shop fees excluded. No approvals, signatures or performed work.</p><Button primary disabled={!isReviewed(state)} onClick={onCustomer} data-testid="open-reviewed-report">Customer report <ArrowRight /></Button><Button disabled={!isReviewed(state)} onClick={() => dispatch({ type: 'handoff' })} data-testid="simulate-handoff">Simulate Protractor handoff</Button><p className="hint">Local demonstration only. No network request. No real ticket is created.</p>{state.handoffRevision === state.revision && <div className="notice success" role="status" data-testid="handoff-result"><strong>Simulated handoff recorded.</strong> No real Protractor ticket was created.</div>}</aside></div>
  </div>;
}
