import { ShieldCheck, FileText } from 'lucide-react';
import { composeInspectionLines, isReviewed, recommendationTotal, ticketTotal, type DemoState } from '../../model';
import { Button, InspectionLines, money, Panel } from './Common';

export function Customer({ state, onAdvisor }: { state: DemoState; onAdvisor: () => void }) {
  const reviewed = isReviewed(state);
  const lines = composeInspectionLines(state);
  const good = lines.filter(l => l.rating === 'green' || l.rating === 'pass').length;
  const attention = lines.filter(l => l.rating === 'yellow' || l.rating === 'red' || l.rating === 'fail').length;
  const notInspected = lines.filter(l => !l.inspected).length;
  return <div data-testid="customer-view"><div className="page-heading"><div><div className="eyebrow">03 / Customer report preview</div><h1>Your vehicle, clearly documented.</h1><p>Fictional report for Rowan Hale. A local preview, not a public link or message.</p></div><span className={`badge ${reviewed ? '' : 'yellow'}`}>{reviewed ? 'Advisor-reviewed preview' : 'Draft · not reviewed'}</span></div>
    {!reviewed && <div className="notice"><strong>This revision has not been reviewed.</strong> Do not present it as a final report. <div className="actions"><Button onClick={onAdvisor}>Return to advisor review</Button></div></div>}
    <div className="report-banner"><div className="row"><ShieldCheck /><span className="eyebrow" style={{ color: 'inherit', margin: 0 }}>{reviewed ? 'Reviewed inspection record' : 'Draft inspection record'}</span></div><h2 style={{ fontSize: 25, marginTop: 15 }}>2019 Meridian S4 · 62,418 miles</h2><p>All documented results matter — including the things that look good.</p><div className="report-summary"><span><strong>{good}</strong> Good / pass</span><span><strong>{attention}</strong> Monitor / attention</span><span><strong>{notInspected}</strong> Not inspected / tested / applicable</span></div></div>
    <div className="layout"><div className="stack"><Panel title="Findings & evidence" description="The same measurements, technician notes and local evidence shown to the advisor."><InspectionLines lines={lines} /></Panel><Panel title="Optional proposed work" description="Recommendations, not authorization or completed repairs.">{state.recommendations.some(r => r.selected) ? <>{state.recommendations.filter(r => r.selected).map(r => <article className="line" key={r.id}><div className="line-top"><h3>{r.title}</h3><span className="badge yellow">Proposed only</span></div><p>{r.part} · {r.quantity} × {money(Number(r.unitPrice) || 0)}</p><p>{r.labor} · {r.hours} hours × {money(Number(r.laborRate) || 0)}</p><div className="total"><span>Package estimate</span><strong>{money(recommendationTotal(r))}</strong></div></article>)}<div className="total"><span>Proposed total · USD, before tax / fees</span><strong>{money(ticketTotal(state))}</strong></div></> : <div className="empty"><ShieldCheck /><h3>No proposed work selected.</h3><p>The inspection record still includes every documented green result. A good visit deserves a complete report.</p></div>}</Panel></div><aside className="guide"><FileText /><h2>A record, not a repair receipt.</h2><p className="hint">The required inspection documentation package is $0.00. Optional work is an estimate only. Nothing here is customer-authorized or performed.</p><div className="section-label">How to read your report</div><p className="hint"><strong>Good / pass:</strong> technician confirmed a good result.<br /><strong>Monitor:</strong> a condition to discuss.<br /><strong>Attention / fail:</strong> a concern to discuss.<br /><strong>Not inspected / tested:</strong> no completed check is claimed.<br /><strong>Not applicable:</strong> excluded with a distinct status, not green.</p><Button onClick={onAdvisor}>Back to advisor</Button><p className="hint">No share links, messages, approvals or signatures. All data and media stay in this browser session.</p></aside></div>
  </div>;
}
