import { useState } from 'react';
import { ArrowRight, ClipboardCheck, FlaskConical } from 'lucide-react';
import { LIBRARY, WHEEL_NAMES, composeInspectionLines, getCompletionErrors, isCompleted, type DemoState, type DemoAction, type WheelId, type Wheel, type Standard, type BatteryResult, type Check } from '../../model';
import { Always, Button, Field, MediaInput, Notes, Panel, Ratings, Status } from './Common';

export function Technician({ state, dispatch, onAdvisor }: { state: DemoState; dispatch: (a: DemoAction) => boolean; onAdvisor: () => void }) {
  const [wheelId, setWheelId] = useState<WheelId>('LF');
  const [showErrors, setShowErrors] = useState(false);
  const [sample, setSample] = useState(false);
  const wheel = state.wheels.find(w => w.id === wheelId)!;
  const wheelName = WHEEL_NAMES[wheelId];
  const patchWheel = (patch: Partial<Omit<Wheel, 'id'>>) => dispatch({ type: 'wheel', id: wheelId, patch });
  const b = state.battery;
  const errors = getCompletionErrors(state);
  const documented = composeInspectionLines(state).filter(l => l.mandatory && (l.inspected || l.rating === 'unable-to-test' && l.notes.trim())).length;
  const required = composeInspectionLines(state).filter(l => l.mandatory).length;
  const checkEditor = (c: Check) => <div className="check-row" key={c.id}><div className="check-title"><h3>{c.name}</h3>{c.mandatory ? <Always /> : <Button aria-label={`Remove optional ${c.name}`} onClick={() => dispatch({ type: 'toggle-check', id: c.id })}>Remove</Button>}</div><Ratings label={c.name} value={c.rating} optional={!c.mandatory} onChange={rating => dispatch({ type: 'check', id: c.id, patch: { rating } })} />{c.id === 'brake-pads' && <div className="fields"><Field label="Brake-pad thickness (mm)" type="number" min={0} max={30} value={c.thickness} onChange={thickness => dispatch({ type: 'check', id: c.id, patch: { thickness } })} /></div>}<Notes label={`${c.name} notes`} value={c.notes} onChange={notes => dispatch({ type: 'check', id: c.id, patch: { notes } })} /><MediaInput label={`${c.name} evidence`} items={c.media} onChange={media => dispatch({ type: 'check', id: c.id, patch: { media } })} /></div>;
  return <div data-testid="technician-view"><div className="page-heading"><div><div className="eyebrow">01 / Technician · Mara Voss</div><h1>Good results deserve a record.</h1><p>Measure by hand. Confirm every result. Give the advisor a complete picture, not just a list of problems.</p></div><span className="badge">Manual inspection</span></div>
    <div className="layout"><div className="stack">
      <Panel title="Four-wheel tire inspection" description="Wheel-specific fitment, tread and pressure. Ratings are never inferred." badge={<Always />}>
        <div className="wheel-layout"><div><div className="vehicle-map" role="group" aria-label="Four-wheel vehicle diagram"><span className="map-front">FRONT OF VEHICLE</span><div className="vehicle-body" aria-hidden="true" />{state.wheels.map(w => <button key={w.id} className={`wheel-btn ${w.id === wheelId ? 'selected' : ''}`} aria-label={`Select ${WHEEL_NAMES[w.id]} tire`} aria-pressed={w.id === wheelId} onClick={() => setWheelId(w.id)}><strong className="mono">{w.id}</strong><Status value={w.rating} /></button>)}</div><p className="hint">Select a wheel to record its actual measurements.</p></div>
          <div data-testid={`wheel-editor-${wheelId}`}><div className="line-top"><h3>{wheelName}</h3><span className="mono muted">{wheelId}</span></div><div className="fields"><Field label={`${wheelName} actual tire size`} value={wheel.size} onChange={size => patchWheel({ size })} /><Field label={`${wheelName} OE / placard reference (optional)`} value={wheel.oeSize} placeholder="Reference only" onChange={oeSize => patchWheel({ oeSize })} /></div>
            <label className="field">{wheelName} tread unit<select aria-label={`${wheelName} tread unit`} value={wheel.unit} onChange={e => patchWheel({ unit: e.target.value as '32nds' | 'mm' })}><option value="32nds">32nds of an inch (/32 in)</option><option value="mm">Millimeters (mm)</option></select></label>
            <p className="hint">Changing units clears the tread readings; no automatic conversion. Re-enter values in the selected unit.</p>
            <div className="fields three">{(['inner', 'center', 'outer'] as const).map((key, i) => <Field key={key} label={`${wheelName} ${['inner', 'center', 'outer'][i]} tread (${wheel.unit === '32nds' ? '/32 in' : 'mm'})`} type="number" min={0} max={wheel.unit === '32nds' ? 32 : 25} value={wheel[key]} onChange={v => patchWheel({ [key]: v })} />)}</div>
            <div className="fields"><Field label={`${wheelName} before pressure (PSI)`} type="number" min={1} max={120} value={wheel.beforePsi} onChange={beforePsi => patchWheel({ beforePsi })} /><Field label={`${wheelName} after pressure (PSI, optional)`} type="number" min={1} max={120} value={wheel.afterPsi} placeholder="Leave blank if not measured" onChange={afterPsi => patchWheel({ afterPsi })} /></div><p className="hint">Before and after are independent readings. A blank after value is not a pressure adjustment claim.</p>
            <Ratings label={wheelName} value={wheel.rating} onChange={rating => patchWheel({ rating })} /><Notes label={`${wheelName} condition notes`} value={wheel.notes} onChange={notes => patchWheel({ notes })} /><MediaInput label={`${wheelName} photo / video evidence`} items={wheel.media} onChange={media => patchWheel({ media })} />
          </div></div>
      </Panel>
      <Panel title="Battery test" description="Record what the tester says. The technician confirms pass or fail." badge={<Always />}>
        <div className="fields"><Field label="Battery rated cranking value" type="number" min={1} max={3000} value={b.rated} onChange={rated => dispatch({ type: 'battery', patch: { rated } })} /><Field label="Battery measured cranking value" type="number" min={1} max={3000} value={b.measured} onChange={measured => dispatch({ type: 'battery', patch: { measured } })} /></div>
        <div className="fields">{(['ratedStandard', 'measuredStandard'] as const).map(key => <label className="field" key={key}>Battery {key === 'ratedStandard' ? 'rated' : 'measured'} standard / unit<select aria-label={`Battery ${key === 'ratedStandard' ? 'rated' : 'measured'} standard / unit`} value={b[key]} onChange={e => dispatch({ type: 'battery', patch: { [key]: e.target.value as Standard } })}>{(['CCA', 'CA', 'EN', 'DIN'] as Standard[]).map(s => <option key={s} value={s}>{s} · cranking amps</option>)}</select></label>)}</div>
        {b.ratedStandard !== b.measuredStandard && <p className="notice error" role="alert">Standards do not match. Retest or record matching values; no cross-standard conversion is performed.</p>}
        <label className="field">Battery technician-entered result<select aria-label="Battery technician-entered result" value={b.result} onChange={e => dispatch({ type: 'battery', patch: { result: e.target.value as BatteryResult } })}><option value="not-tested">Not tested</option><option value="pass">Pass · manually confirmed</option><option value="fail">Fail · manually confirmed</option><option value="unable-to-test">Unable to test · explanation required</option></select></label><p className="hint">No percentage threshold, rating inference or automatic pass/fail. Unable to test is documented, never called a completed test.</p>
        <div className="fields"><Field label="Battery voltage (V, optional)" type="number" min={0} max={60} value={b.voltage} onChange={voltage => dispatch({ type: 'battery', patch: { voltage } })} /><Field label="Battery terminal condition (optional)" value={b.terminals} onChange={terminals => dispatch({ type: 'battery', patch: { terminals } })} /></div>
        <Notes label="Battery notes / unable-to-test explanation" value={b.notes} onChange={notes => dispatch({ type: 'battery', patch: { notes } })} /><MediaInput label="Battery local test-printout image" imageOnly items={b.media} onChange={media => dispatch({ type: 'battery', patch: { media } })} />
      </Panel>
      <Panel title="Fixed safety checks" description="Two required visual checks for this fictional demonstration; not an enterprise policy template." badge={<Always />}>{state.checks.filter(c => c.mandatory).map(checkEditor)}</Panel>
      <Panel title="Optional checklist library" description="Suggested demo options only. Not enterprise-approved mandatory checks."><div className="library">{[...new Set(LIBRARY.map(c => c.group))].map(group => <details key={group}><summary>{group}</summary>{LIBRARY.filter(c => c.group === group).map(c => <label className="library-option" key={c.id}><input type="checkbox" aria-label={`Include ${c.name}`} checked={state.checks.some(item => item.id === c.id)} onChange={() => dispatch({ type: 'toggle-check', id: c.id })} />{c.name}</label>)}</details>)}</div>{state.checks.filter(c => !c.mandatory).length > 0 && <div style={{ marginTop: 22 }}>{state.checks.filter(c => !c.mandatory).map(checkEditor)}</div>}</Panel>
      {showErrors && errors.length > 0 && <div className="notice error" role="alert" data-testid="completion-errors"><strong>Finish the required documentation</strong><ul>{errors.map(e => <li key={e}>{e}</li>)}</ul></div>}
      <div className="sticky-actions"><div><strong>{isCompleted(state) ? 'Inspection documentation complete' : 'Ready when the record is complete'}</strong><p>All mandatory green results stay in the package.</p></div><Button primary data-testid="complete-inspection" onClick={() => { setShowErrors(true); if (dispatch({ type: 'complete' })) onAdvisor(); }}>Complete inspection <ArrowRight /></Button></div>
    </div><aside className="guide"><ClipboardCheck /><div className="eyebrow" style={{ marginTop: 15 }}>Documentation coverage</div><div className="large-stat">{documented}<small> / {required}</small></div><div className="progress-track"><span style={{ width: `${documented / required * 100}%` }} /></div><h2>Every required result.<br />Even the good ones.</h2><p className="hint">Tires, battery and fixed safety checks cannot be deselected. Values are validated when you complete the record.</p><ol><li>Enter four wheel-specific readings.</li><li>Record the battery result and values.</li><li>Confirm safety checks, then complete.</li></ol><div className="section-label">Presenter shortcut</div><Button onClick={() => setSample(!sample)} data-testid="sample-findings"><FlaskConical /> Sample AI findings</Button><p className="hint">Fictional preset only. Does not analyze your files or call AI.</p>{sample && <div className="sample"><strong>Review fictional sample</strong><p>Four green tires: 7 / 8 / 7 /32 in, 34 PSI before, after unrecorded. Battery: 760 rated / 724 measured CCA, manual pass, 12.6 V. Both safety checks green. Tire sizes and evidence remain unchanged.</p><p className="hint">Confirm only to populate demo fields. Not a real inspection.</p><Button primary data-testid="confirm-sample" onClick={() => { dispatch({ type: 'sample-green' }); setSample(false); }}>Confirm fictional findings</Button><Button onClick={() => setSample(false)}>Discard sample</Button></div>}</aside></div>
  </div>;
}
