// Drizzle schema for the concern follow-up question cache (task #1139).
// Mirrors drizzle/0029_task1139_concern_followup_cache.sql.
// Hand-written — db:generate is dead (journal drift since 0012); see
// drizzle-migration-path memory for context.
import {
  pgTable,
  varchar,
  text,
  jsonb,
  timestamp,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const concernFollowupCache = pgTable("concern_followup_cache", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  /** sha256(normalized_concern + ":" + prompt_version), hex-truncated to 32 chars. */
  concernHash: text("concern_hash").notNull(),
  /** Array of question strings generated by OpenAI. */
  questions: jsonb("questions").$type<string[]>().notNull(),
  /** Version tag for the prompt/guide — bump when guide or prompt template changes. */
  promptVersion: text("prompt_version").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
}, (t) => ({
  concernHashIdx: uniqueIndex("cfc_concern_hash_idx").on(t.concernHash),
  createdAtIdx: index("cfc_created_at_idx").on(t.createdAt),
}));
