import {
  pgTable,
  text,
  varchar,
  timestamp,
  integer,
  boolean,
  jsonb,
  decimal,
  index,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const crmAgencies = pgTable("crm_agencies", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  slug: text("slug").notNull().unique(),
  type: text("type").notNull().default("marketing"),
  status: text("status").notNull().default("Active"),
  logo: text("logo"),
  primaryColor: text("primary_color").default("#3c81c3"),
  secondaryColor: text("secondary_color").default("#1e5a8a"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  stripeAccountId: text("stripe_account_id"),
  stripeOnboarded: boolean("stripe_onboarded").default(false),
  commissionRate: decimal("commission_rate", { precision: 5, scale: 2 }).default("10.00"),
  favicon: text("favicon"),
  avatar: text("avatar"),
  tagline: text("tagline"),
  slogan: text("slogan"),
  corporateWebsite: text("corporate_website"),
  appStoreLink: text("app_store_link"),
  playStoreLink: text("play_store_link"),
  brandingThemeId: varchar("branding_theme_id"),
  headerColor: text("header_color"),
  buttonColor: text("button_color"),
  buttonTextColor: text("button_text_color"),
  borderColor: text("border_color"),
  accentColor: text("accent_color"),
  backgroundColor: text("background_color"),
  sidebarColor: text("sidebar_color"),
  cardColor: text("card_color"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  archivedAt: timestamp("archived_at"),
}, (table) => ({
  slugIdx: index("crm_agencies_slug_idx").on(table.slug),
  statusIdx: index("crm_agencies_status_idx").on(table.status),
}));

export const crmCorporateBranding = pgTable("crm_corporate_branding", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  logo: text("logo"),
  favicon: text("favicon"),
  avatar: text("avatar"),
  companyName: text("company_name").default("MOS Tools"),
  tagline: text("tagline"),
  slogan: text("slogan"),
  corporateWebsite: text("corporate_website"),
  appStoreLink: text("app_store_link"),
  playStoreLink: text("play_store_link"),
  activeThemeId: varchar("active_theme_id"),
  primaryColor: text("primary_color").default("#3c81c3"),
  secondaryColor: text("secondary_color").default("#1e5a8a"),
  headerColor: text("header_color").default("#ffffff"),
  headerTextColor: text("header_text_color").default("#1f2937"),
  buttonColor: text("button_color").default("#3c81c3"),
  buttonTextColor: text("button_text_color").default("#ffffff"),
  buttonHoverColor: text("button_hover_color").default("#1e5a8a"),
  borderColor: text("border_color").default("#e5e7eb"),
  accentColor: text("accent_color").default("#7ab3e0"),
  backgroundColor: text("background_color").default("#f9fafb"),
  sidebarColor: text("sidebar_color").default("#ffffff"),
  sidebarTextColor: text("sidebar_text_color").default("#374151"),
  sidebarActiveColor: text("sidebar_active_color").default("#f3f4f6"),
  cardColor: text("card_color").default("#ffffff"),
  cardBorderColor: text("card_border_color").default("#e5e7eb"),
  mutedColor: text("muted_color").default("#6b7280"),
  destructiveColor: text("destructive_color").default("#ef4444"),
  successColor: text("success_color").default("#22c55e"),
  warningColor: text("warning_color").default("#f59e0b"),
  infoColor: text("info_color").default("#3b82f6"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  updatedBy: varchar("updated_by"),
});

export const crmBrandingThemes = pgTable("crm_branding_themes", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  description: text("description"),
  isDefault: boolean("is_default").default(false),
  isLocked: boolean("is_locked").default(false),
  previewPrimary: text("preview_primary").notNull(),
  previewSecondary: text("preview_secondary").notNull(),
  previewAccent: text("preview_accent"),
  primaryColor: text("primary_color").notNull(),
  secondaryColor: text("secondary_color").notNull(),
  headerColor: text("header_color"),
  headerTextColor: text("header_text_color"),
  buttonColor: text("button_color"),
  buttonTextColor: text("button_text_color"),
  buttonHoverColor: text("button_hover_color"),
  borderColor: text("border_color"),
  accentColor: text("accent_color"),
  backgroundColor: text("background_color"),
  sidebarColor: text("sidebar_color"),
  sidebarTextColor: text("sidebar_text_color"),
  sidebarActiveColor: text("sidebar_active_color"),
  cardColor: text("card_color"),
  cardBorderColor: text("card_border_color"),
  mutedColor: text("muted_color"),
  destructiveColor: text("destructive_color"),
  successColor: text("success_color"),
  warningColor: text("warning_color"),
  infoColor: text("info_color"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  createdBy: varchar("created_by"),
});

export const crmParentOrganizations = pgTable("crm_parent_organizations", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  agencyId: varchar("agency_id").references(() => crmAgencies.id),
  status: text("status").notNull().default("Active"),
  contactName: text("contact_name"),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  notes: text("notes"),
  logo: text("logo"),
  favicon: text("favicon"),
  avatar: text("avatar"),
  tagline: text("tagline"),
  slogan: text("slogan"),
  corporateWebsite: text("corporate_website"),
  brandingThemeId: varchar("branding_theme_id"),
  primaryColor: text("primary_color"),
  secondaryColor: text("secondary_color"),
  headerColor: text("header_color"),
  buttonColor: text("button_color"),
  buttonTextColor: text("button_text_color"),
  borderColor: text("border_color"),
  accentColor: text("accent_color"),
  backgroundColor: text("background_color"),
  sidebarColor: text("sidebar_color"),
  cardColor: text("card_color"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  archivedAt: timestamp("archived_at"),
}, (table) => ({
  agencyIdx: index("crm_parent_orgs_agency_idx").on(table.agencyId),
  statusIdx: index("crm_parent_orgs_status_idx").on(table.status),
}));

export const crmAccounts = pgTable("crm_accounts", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  parentOrganizationId: varchar("parent_organization_id").references(() => crmParentOrganizations.id),
  agencyId: varchar("agency_id").references(() => crmAgencies.id),
  plan: text("plan").notNull().default("Growth"),
  status: text("status").notNull().default("Active"),
  ownerName: text("owner_name"),
  ownerEmail: text("owner_email"),
  ownerPhone: text("owner_phone"),
  linkedShopId: integer("linked_shop_id"),
  smsNumber: text("sms_number"),
  notes: text("notes"),
  sms: text("sms"),
  nextBilling: timestamp("next_billing"),
  logo: text("logo"),
  favicon: text("favicon"),
  avatar: text("avatar"),
  tagline: text("tagline"),
  slogan: text("slogan"),
  corporateWebsite: text("corporate_website"),
  brandingThemeId: varchar("branding_theme_id"),
  primaryColor: text("primary_color"),
  secondaryColor: text("secondary_color"),
  headerColor: text("header_color"),
  buttonColor: text("button_color"),
  buttonTextColor: text("button_text_color"),
  borderColor: text("border_color"),
  accentColor: text("accent_color"),
  backgroundColor: text("background_color"),
  sidebarColor: text("sidebar_color"),
  cardColor: text("card_color"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  archivedAt: timestamp("archived_at"),
}, (table) => ({
  parentOrgIdx: index("crm_accounts_parent_org_idx").on(table.parentOrganizationId),
  agencyIdx: index("crm_accounts_agency_idx").on(table.agencyId),
  statusIdx: index("crm_accounts_status_idx").on(table.status),
  planIdx: index("crm_accounts_plan_idx").on(table.plan),
}));

export const crmLocations = pgTable("crm_locations", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  accountId: varchar("account_id").notNull().references(() => crmAccounts.id, { onDelete: "cascade" }),
  parentOrganizationId: varchar("parent_organization_id").references(() => crmParentOrganizations.id),
  agencyId: varchar("agency_id").references(() => crmAgencies.id),
  name: text("name").notNull(),
  address: text("address"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  phone: text("phone"),
  timezone: text("timezone").default("America/Chicago"),
  smsNumber: text("sms_number"),
  linkedShopId: integer("linked_shop_id"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  archivedAt: timestamp("archived_at"),
}, (table) => ({
  accountIdx: index("crm_locations_account_idx").on(table.accountId),
  parentOrgIdx: index("crm_locations_parent_org_idx").on(table.parentOrganizationId),
}));

export const crmUserTypes = pgTable("crm_user_types", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: text("name").notNull(),
  bucket: text("bucket").notNull().default("account"),
  description: text("description"),
  permissions: jsonb("permissions").$type<Record<string, boolean>>().default(sql`'{}'::jsonb`),
  sortOrder: integer("sort_order").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const crmAgencyPricingPackages = pgTable("crm_agency_pricing_packages", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  agencyId: varchar("agency_id").notNull().references(() => crmAgencies.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  description: text("description"),
  monthlyPrice: decimal("monthly_price", { precision: 10, scale: 2 }).notNull(),
  features: text("features").array(),
  isActive: boolean("is_active").notNull().default(true),
  sortOrder: integer("sort_order").default(0),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type CrmAgency = typeof crmAgencies.$inferSelect;
export type CrmCorporateBranding = typeof crmCorporateBranding.$inferSelect;
export type CrmBrandingTheme = typeof crmBrandingThemes.$inferSelect;
export type CrmParentOrganization = typeof crmParentOrganizations.$inferSelect;
export type CrmAccount = typeof crmAccounts.$inferSelect;
export type CrmLocation = typeof crmLocations.$inferSelect;
export type CrmUserType = typeof crmUserTypes.$inferSelect;
export type CrmAgencyPricingPackage = typeof crmAgencyPricingPackages.$inferSelect;
