import {test,expect} from '@playwright/test';
test('complete presentation, evidence, pricing, reset and network isolation',async({page,baseURL})=>{
  const forbidden:string[]=[];
  const errors:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{
    if(r.url().startsWith('blob:')||r.url().startsWith('data:'))return;
    if(new URL(r.url()).origin!==new URL(baseURL!).origin || /\/api\//.test(r.url()) || r.method()!=='GET')forbidden.push(r.url());
  });
  await page.goto('./');
  await page.getByTestId('complete-inspection').click();
  await expect(page.getByTestId('completion-errors')).toContainText('Left front');
  await page.getByTestId('sample-findings').click();
  await expect(page.getByLabel('Left front inner tread (/32 in)',{exact:true})).toHaveValue('');
  await page.getByTestId('confirm-sample').click();
  await expect(page.getByLabel('Left front after pressure (PSI, optional)',{exact:true})).toHaveValue('');
  await page.getByLabel('Left front before pressure (PSI)',{exact:true}).fill('35');
  await expect(page.getByLabel('Left front after pressure (PSI, optional)',{exact:true})).toHaveValue('');
  await page.getByLabel('Left front photo / video evidence',{exact:true}).setInputFiles({name:'tire.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});
  await expect(page.getByAltText('Local evidence: tire.png')).toBeVisible();
  await page.getByLabel('Left front photo / video evidence',{exact:true}).setInputFiles('tests/fixtures/local-demo.webm');
  await expect(page.getByLabel('Local video: local-demo.webm',{exact:true})).toBeVisible();
  await expect.poll(()=>page.getByLabel('Local video: local-demo.webm',{exact:true}).evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThan(0);
  await page.getByTestId('complete-inspection').click();
  await expect(page.getByTestId('advisor-view')).toBeVisible();
  await expect(page.getByTestId('line-wheel-LF')).toContainText('35 PSI');
  await expect(page.getByTestId('line-battery')).toContainText('724 CCA');
  await expect(page.locator('[data-testid^="line-"]')).toHaveCount(7);
  await page.getByTestId('review-ticket').click();
  await page.getByTestId('open-reviewed-report').click();
  await expect(page.getByTestId('customer-view')).toContainText('No proposed work selected');
  await expect(page.getByAltText('Local evidence: tire.png')).toBeVisible();
  await expect(page.getByLabel('Local video: local-demo.webm',{exact:true})).toBeVisible();
  await page.getByTestId('nav-advisor').click();
  await page.getByLabel('Include Rear tire replacement recommendation',{exact:true}).check();
  await expect(page.getByTestId('ticket-total')).toHaveText('$470.50');
  await page.getByLabel('tires parts quantity',{exact:true}).fill('3');
  await expect(page.getByTestId('ticket-total')).toHaveText('$657.95');
  await expect(page.getByTestId('review-ticket')).toBeDisabled();
  await page.getByTestId('nav-technician').click();
  await page.getByLabel('Battery measured standard / unit',{exact:true}).selectOption('EN');
  await page.getByTestId('complete-inspection').click();
  await expect(page.getByTestId('completion-errors')).toContainText('standards must match');
  await page.getByLabel('Battery measured standard / unit',{exact:true}).selectOption('CCA');
  await page.getByLabel('Battery technician-entered result',{exact:true}).selectOption('not-tested');
  await page.getByTestId('complete-inspection').click();
  await expect(page.getByTestId('completion-errors')).toContainText('record a manual pass/fail');
  await page.getByLabel('Battery technician-entered result',{exact:true}).selectOption('pass');
  await page.getByTestId('complete-inspection').click();
  await page.getByTestId('review-ticket').click();
  await page.getByTestId('simulate-handoff').click();
  await expect(page.getByTestId('handoff-result')).toContainText('No real Protractor ticket was created');
  await page.setViewportSize({width:390,height:844});
  for(const view of ['technician','advisor','customer']){
    await page.getByTestId(`nav-${view}`).click();
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  }
  await page.getByTestId('reset-demo').click();
  await page.getByTestId('confirm-reset').click();
  await expect(page.getByLabel('Left front inner tread (/32 in)',{exact:true})).toHaveValue('');
  await expect(page.getByAltText('Local evidence: tire.png')).toHaveCount(0);
  expect(forbidden).toEqual([]);
  expect(errors).toEqual([]);
});
