const {chromium}=require("../../artifacts/detect-dog-workflow/node_modules/@playwright/test");
const assert=require("node:assert/strict");
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.DEMO_CHROMIUM_PATH,headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[],requests=[];
 page.on("pageerror",e=>errors.push(e.message));page.on("request",r=>requests.push(r.url()));
 await page.goto("http://127.0.0.1:24100");
 const id=s=>page.getByTestId(s);
 await id("visit-visit").click();
 const transport=id("transport-form");
 await transport.locator('[name="customerPlan"]').selectOption("waiting");
 await transport.locator('[name="ride"]').selectOption("needed");
 await transport.locator('[name="loaner"]').selectOption("requested");
 await transport.getByRole("button",{name:"Save customer plan"}).click();
 await transport.getByRole("status").filter({hasText:"Saved"}).waitFor();
 await id("start-job").click();
  await page.getByText("Pause with a reason",{exact:true}).click();
 await page.getByTestId("pause-form-job").locator('[name="reason"]').fill("Waiting for parts");
 await id("pause-form-job").getByRole("button",{name:"Pause work"}).click();
 await id("start-job").waitFor();
 await id("start-job").click();
 await id("complete-job").click();
 await id("pilot-manage").click();
 const create=id("visit-create-form");
 await create.locator('[name="ro"]').fill("TEST-002");
 await create.locator('[name="vehicle"]').fill("Second test vehicle");
 await create.getByRole("button",{name:"Create visit"}).click();
 await create.getByRole("status").filter({hasText:"Saved"}).waitFor();
 await id("pilot-settings").click();
 await id("location-brand-form").waitFor();
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await id("pilot-dispatch").click();
 await id("visit-visit").click();
 await id("transport-form").waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 assert.equal(requests.some(u=>!u.startsWith("http://127.0.0.1:24100")&&!u.startsWith("data:")),false);
 await browser.close();console.log("Offline pilot UI: transport save, start/pause/resume/complete, visit creation and mobile layouts passed; no production requests.");
})().catch(e=>{console.error(e);process.exit(1);});
